# Generated by Django 3.2.13 on 2023-04-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('ratings', models.IntegerField()),
                ('total_review_count', models.IntegerField()),
                ('website', models.URLField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
