# Generated by Django 3.2.13 on 2023-04-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
