# Generated by Django 3.2.13 on 2023-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkl', '0002_auto_20230421_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
